name: Merge with develop branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

      
jobs:
  dev-pr-merge:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0 
    - name: Release Please
      id: release_action_plan
      uses: google-github-actions/release-please-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config-file: .github/configuration/release-please-config.json
        manifest-file: .github/configuration/release-please-manifest.json
    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"        
            